import React, { useEffect, useState } from "react";
import api from "../api";

const Enquiries = () => {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState("all"); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(null);
  const load = () => { setLoading(true); api.get(`/api/inquiries?status=${filter}`).then((res)=>setItems(res.data||[])).catch((err)=>alert(err.response?.data?.error||"Enquiries could not be loaded")).finally(()=>setLoading(false)); };
  useEffect(load,[filter]);
  const update = async (item, patch) => { const res=await api.patch(`/api/inquiries/${item._id}`,patch); setItems((current)=>current.map((row)=>row._id===item._id?res.data:row)); setSelected((current)=>current?res.data:null); };
  const open = (item) => { setSelected(item); if(!item.readAt) update(item,{readAt:new Date().toISOString()}); };
  const remove = async (item) => { if(!window.confirm("Delete this enquiry permanently?"))return; await api.delete(`/api/inquiries/${item._id}`); setItems((current)=>current.filter((row)=>row._id!==item._id)); setSelected(null); };
  return <div className="page-wrap enquiries-page"><header className="page-head"><div><span className="eyebrow">LEAD INBOX</span><h1>Website enquiries</h1><p>View and manage leads received from your live websites.</p></div><select value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="all">All enquiries</option><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option><option value="spam">Spam</option></select></header>
    <div className="enquiry-layout"><section className="panel enquiry-list">{loading?<div className="empty-state">Loading enquiries...</div>:items.length?items.map((item)=><button key={item._id} className={`enquiry-item ${!item.readAt?"unread":""} ${selected?._id===item._id?"active":""}`} onClick={()=>open(item)}><span className="lead-avatar">{item.name?.charAt(0).toUpperCase()}</span><span><strong>{item.name}</strong><small>{item.subject||item.message.slice(0,65)}</small><i>{item.websiteDomain||"Website"} · {new Date(item.createdAt).toLocaleString()}</i></span><em className={`lead-status ${item.status}`}>{item.status}</em></button>):<div className="empty-state"><h3>No enquiries yet</h3><p>New website leads will appear here.</p></div>}</section>
    <aside className="panel enquiry-detail">{selected?<><div className="detail-head"><div><span className="eyebrow">ENQUIRY DETAILS</span><h2>{selected.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><dl><div><dt>Email</dt><dd>{selected.email?<a href={`mailto:${selected.email}`}>{selected.email}</a>:"—"}</dd></div><div><dt>Phone</dt><dd>{selected.phone?<a href={`tel:${selected.phone}`}>{selected.phone}</a>:"—"}</dd></div><div><dt>Company</dt><dd>{selected.company||"—"}</dd></div><div><dt>Website</dt><dd>{selected.websiteDomain||"—"}</dd></div><div><dt>Source page</dt><dd>{selected.sourcePage||"—"}</dd></div></dl><div className="lead-message"><strong>{selected.subject||"Message"}</strong><p>{selected.message}</p></div><label>Status<select value={selected.status} onChange={(e)=>update(selected,{status:e.target.value})}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option><option value="spam">Spam</option></select></label><label>Private notes<textarea value={selected.notes||""} onChange={(e)=>setSelected({...selected,notes:e.target.value})} onBlur={()=>update(selected,{notes:selected.notes||""})} placeholder="Add follow-up notes..." /></label><div className="lead-actions">{selected.email&&<a href={`mailto:${selected.email}`}>Reply by email</a>}{selected.phone&&<a href={`https://wa.me/${selected.phone.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp</a>}<button onClick={()=>remove(selected)}>Delete</button></div></>:<div className="empty-state"><h3>Select an enquiry</h3><p>Lead details and follow-up actions will appear here.</p></div>}</aside></div>
  </div>;
};
export default Enquiries;
